#!/bin/sh

echo "cleaning distribution"
rm -f *.dvi *.bbl *.aux *.log *.blg *.toc *.lof *.lot *.glo *.ilg *.gls *.out
rm -rf `find . -name auto`
rm -rf `find . -name "*~"`

echo "creating tarball for aiaa-$1"
cd .. && \
cp -r aiaa aiaa-$1 && \
cd aiaa-$1 && \
rm -rf `find . -name CVS` && \
cd .. && \
tar zcf aiaa-$1.tar.gz aiaa-$1 && \
rm -rf aiaa-$1
